# Generated by Django 5.1.2 on 2024-10-22 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_relatedvideo_video_review_instructor_video_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.instructor'),
        ),
    ]
